### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by ghost** [ylyra/sihb#2]
Opa, as rotas não carregaram. Imagina o que possa ser? 
![image](https://user-images.githubusercontent.com/89428643/156261932-db095d44-42fe-4036-8cf6-4bc6005d08d6.png)
Isso occore quando tento acessar qualquer rota, nesse caso:
http://192.168.18.17/sihb/sobre/historia

**Comment by ylyra** [comment]
O .htaccess e config.php foram editados de acordo?

No htaccess essa parte: `RewriteRule ^(.*)$ /sihb/sihb/index.php?url=$1 [QSA,L]` deve estar assim `RewriteRule ^(.*)$ /sihb/index.php?url=$1 [QSA,L]`

E no config.php nessa parte `define("BASE", "http://localhost/sihb/sihb/");` deve ficar assim `define("BASE", "http://192.168.18.17/sihb/");`

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/89428643/156397702-647d143e-f85d-4fb7-8825-36ba7afbdbea.png)
Ficou assim.
![image](https://user-images.githubusercontent.com/89428643/156397929-c999479a-4e1d-44f5-905f-130ee0b0aa43.png)
Colocando o parâmetro ?url=1 no index.php recebo isso.
De resto, todas as outras rotas dão 404.



Edit:
![image](https://user-images.githubusercontent.com/89428643/156398037-e9076b04-3654-4e80-9293-5bed0f87c9be.png)
Esse é o config.php

Os diretórios na pasta do apache:
![image](https://user-images.githubusercontent.com/89428643/156398248-8fc60516-4c9e-4a35-90d4-84aa5daf0b23.png)

**Comment by Sigmw** [comment]
![image](https://user-images.githubusercontent.com/89428643/156423125-8dbe7212-24d0-414a-843c-231b528201d6.png)
Se liga, isso é quando eu entro em uma rota que existe.
`O link na página referida parece estar com algum erro ou desatualizado.`


Agora, quando entro em uma rota que não existe:
![image](https://user-images.githubusercontent.com/89428643/156423412-c6104458-b15a-4b0b-bf8b-d546adf87b8f.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/89428643/156423854-924b0682-ba08-4796-9327-03da698eef96.png)
Aliás, eu consigo entrar nas rotas de boa se eu passar o caminho no parâmetro URL.

**Comment by ylyra** [comment]
se está conseguindo acessa as rotas passando o parâmetro na URL então acredito que o problema é no `.htaccess` não estar rodando

**Comment by ylyra** [comment]
Dá uma pesquisada para ver se o seu ambiente precisa ativa algo para o htaccess funciona (por padrão já deveria)

**Comment by ghost** [comment]
Valeu aí! Estava usando um apache custom do AUR, funcionou aqui.

**Comment by ghost** [comment]
Aliás, qual tua senha lá?
